theme: jekyll-theme-cayman
title: VRC-LT
description: VRChat内でLTをします！
gems:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
  values:
    image: /assets/ogp.png
    logo: /assets/ogp.png
lang: ja_JP
twitter:
  card: summary
